### ISSUE TITLE
Multiple users cannot converse with bot

### ISSUE THREAD

**Issue by trueserve** [mishalhossin/Discord-Chatbot-Gpt4Free#26]
As of the latest updates using `usesless`, if multiple users try to interact with the bot, the following error appears and no response to the query is sent from the bot:

```
Traceback (most recent call last):
  File "/installpath/Discord-Chatbot-Gpt4Free/venv/lib/python3.9/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/installpath/Discord-Chatbot-Gpt4Free/main.py", line 45, in on_message
    await process_user_input(message)
  File "/installpath/Discord-Chatbot-Gpt4Free/main.py", line 34, in process_user_input
    req = usesless.Completion.create(prompt=prompt, parentMessageId=message_id)
  File "/installpath/Discord-Chatbot-Gpt4Free/venv/lib/python3.9/site-packages/gpt4free/usesless/__init__.py", line 46, in create
    response = Completion.__response_to_json(content)
  File "/installpath/Discord-Chatbot-Gpt4Free/venv/lib/python3.9/site-packages/gpt4free/usesless/__init__.py", line 53, in __response_to_json
    split_text = text.rsplit("\n", 1)[1]
IndexError: list index out of range
```

Additionally, the `!pfp` command no longer works.

**Comment by mishalhossin** [comment]
i will look into it

**Comment by mishalhossin** [comment]
I have realized it better to fix problems than to avoid them

**Comment by ImN3k0** [comment]
i'm having this issue as well. i deleted and recloned and still have the same issue. any word on a fix?
