### ISSUE TITLE
Bug: error

### ISSUE THREAD

**Issue by YIRU69** [mishalhossin/Discord-Chatbot-Gpt4Free#29]
```
C:\Users\Desktop\Discord-Chatbot-Gpt4Free-Theb>python main.py
[2023-05-04 20:13:39] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "C:\Users\Desktop\Discord-Chatbot-Gpt4Free-Theb\main.py", line 147, in <module>
    bot.run(TOKEN)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 860, in run
 * Serving Flask app "keep_alive" (lazy loading)
    asyncio.run(runner())
 * Environment: production
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
   WARNING: This is a development server. Do not use it in a production deployment.    return loop.run_until_complete(main)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete

    return future.result()
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 849, in runner
   Use a production WSGI server instead.    await self.start(token, reconnect=reconnect)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 777, in start

 * Debug mode: off
    await self.login(token)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 609, in login
    raise TypeError(f'expected token to be a str, received {token.__class__.__name__} instead')
TypeError: expected token to be a str, received NoneType instead
 * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
 *
 ```

**Comment by mishalhossin** [comment]
Bro create a `.env` file like this 
```
DISCORD_TOKEN=token_from_step_3
```

**Comment by mishalhossin** [comment]
Its not a bug

**Comment by mishalhossin** [comment]
[Step 3](https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free#step-3--getting-discord-bot-token-and-enabling-intents-from-here)

**Comment by YIRU69** [comment]
I fininsh this step. But it can't work.

**Comment by YIRU69** [comment]
I create a new bot. It also doesn't work.
```
[2023-05-04 20:43:35] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "C:\Users\Desktop\Discord-Chatbot-Gpt4Free-Theb\main.py", line 147, in <module>
    bot.run(TOKEN)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 860, in run
 * Serving Flask app "keep_alive" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
```

**Comment by mishalhossin** [comment]
> Maybe be I ignore some set for the discord bot?

at `bot.run(TOKEN)` _(at end of main.py btw)_
you can use `bot.run("ACTUAL_DISCORD_BOT_TOKEN")`
but using a `.env` is much better. I guess you can do what ever you want
I hope you are running this localy

**Comment by mishalhossin** [comment]
have you actually gotten token from here ? 
![image](https://user-images.githubusercontent.com/91066601/236210769-497bb50c-6480-4dcf-b421-de7b12910574.png)

**Comment by YIRU69** [comment]
Yes, I got token here.

**Comment by YIRU69** [comment]
In the `example.env` file? Or just create `.env` file?

**Comment by YIRU69** [comment]
It worked when I just create .env file. Thank you so much!
