### ISSUE TITLE
!bonk command no longer works

### ISSUE THREAD

**Issue by trueserve** [mishalhossin/Discord-Chatbot-Gpt4Free#36]
For several commits now, `!bonk` does not work. After using it, the bot will not respond.

Looks like the command is clearing the chatlog variables incorrectly.

Relevant error logs:
```
2023-05-04 20:32:14 ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "/installpath/Discord-Chatbot-Gpt4Free/venv/lib/python3.9/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/installpath/Discord-Chatbot-Gpt4Free/main.py", line 47, in on_message
    message_history[author_type].append(message.content)
KeyError: 'b'
2023-05-04 20:32:50 ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "/installpath/Discord-Chatbot-Gpt4Free/venv/lib/python3.9/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/installpath/Discord-Chatbot-Gpt4Free/main.py", line 47, in on_message
    message_history[author_type].append(message.content)
KeyError: 'user'
```

**Comment by mishalhossin** [comment]
Cope and update your cloned repo
