### ISSUE TITLE
Enable to start the bot

### ISSUE THREAD

**Issue by mashwishi** [mishalhossin/Discord-Chatbot-Gpt4Free#53]
Steps I did on running:

1. Filled out the .env file
2. pip3 install -r requirements.txt (Successful installed modules)
3. python3 main.py
It runs with the console out:
```log
2023-05-11 12:43:47 INFO     discord.client logging in using static token
 * Serving Flask app 'keep_alive'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3000
 * Running on http://192.168.1.7:3000
Press CTRL+C to quit
Traceback (most recent call last):
  File "/Users/mashwishi/Documents/GitHub/Mechi-Discord/main.py", line 234, in <module>
    bot.run(TOKEN)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/client.py", line 778, in start
    await self.connect(reconnect=reconnect)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/client.py", line 704, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
```
4. Invited the bot. with permission 8 (Administrator) 

Since I have followed every single steps, I am expecting this to run smoothly. However the bot is still offline and not running while website is working fine and accessible

**Comment by zukixa** [comment]
https://discordpy.readthedocs.io/en/stable/intents.html

**Comment by mashwishi** [comment]
Thanks or letting me know!

![image](https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free/assets/62344860/0199d676-0636-4cab-b6dd-b7a5312010eb)

**Comment by mishalhossin** [comment]
Damn
